appName: mongo
namespace: helm
replicaCount: 1
container:
  appName: mongo
  labelName: mongo
  port: 27017
image:
  repository: mongo
  tag: "latest"
service:
  name: mongo
  type: ClusterIP
  port: 27017
  targetPort: 27017
livenessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5
