appName: backend
namespace: helm
replicaCount: 2
container:
  appName: backend
  labelName: backend
  port: 3001
image:
  repository: robintyagi27/helm-backend
  tag: "latest"

env:
  - name: ATLAS_URI
    value: "mongodb+srv://robintyagi:q6gL9MDzZiW291fC@ranya-cluster.auw6kfz.mongodb.net/?retryWrites=true&w=majority&appName=robintyagi-cluster"
  - name: HASH_KEY
    value: "fce5dbe91f227224cb1e183057f95c62cc12c0b722efeee824ad29564d654d7e"
  - name: JWT_SECRET_KEY
    value: "bb2e8d3843e9f20e8fb64ea859b3fcb9cb1dad055b309d00debb304ab75e63f701ad4c5f32524a0176a6f8d7
b45a79f1bf87b90028c280a2e24cac0cd1f9ca8f"      

service:
  name: backend
  type: ClusterIP
  port: 3001
  targetPort: 3001
livenessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5
