appName: frontend
namespace: helm
replicaCount: 2
container:
  appName: frontend
  labelName: frontend
  port: 3000
image:
  repository: robintyagi27/helm-frontend
  tag: "latest"

env:
  - name: REACT_APP_API_URL
    value: "http://backend:3001"

service:
  name: frontend
  type: NodePort
  port: 80
  targetPort: 3000
  container_port: 30000

livenessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5
